Version 2
Open-Systems-Pharmacology/Pediatric_Qualification_Package_UGT1A9_Ontogeny pull request #4
Opened 2023-02-16 10:29 UTC by Incei

…revious review.

2023-02-16 10:29 UTC, Incei commented
@AndreDlm

2023-02-16 15:33 UTC, Yuri05 commented on Input/Qualification-Ontogeny-UGT1A9.json
>              "Path": "https://raw.githubusercontent.com/Open-Systems-Pharmacology/Propofol-Model/master/Propofol.json",
PAth must be replace with the reference to the released version (once Propofol is released).
Will create an issue for that.

2023-02-16 15:33 UTC, Yuri05 commented on Input/Qualification-Ontogeny-UGT1A9.json
> +            "Path": "https://raw.githubusercontent.com/Open-Systems-Pharmacology/Propofol-Pediatrics/main/Propofol-Pediatrics.json",
same

2023-02-16 15:33 UTC, Yuri05 commented on Input/Qualification-Ontogeny-UGT1A9.json
> +            "Path": "https://raw.githubusercontent.com/Open-Systems-Pharmacology/Database-for-observed-data/master/Pediatrics.csv",
same

2023-02-16 16:29 UTC, Yuri05 requested changes
Workflow.R is not saved as UTF-8 and makes problems.
Please save as UTF-8

2023-02-16 16:48 UTC, Yuri05 commented
should it look like this?
![grafik](https://user-images.githubusercontent.com/25061876/219432395-f8115798-527f-4882-8370-6e94aeced6b8.png)

2023-02-16 17:30 UTC, Yuri05 commented
<img width="400" src="https://user-images.githubusercontent.com/25061876/219432642-7ec9937d-0a6f-4bfb-afea-5671d51109ea.png">

please use either a picture for GMFE (https://github.com/Open-Systems-Pharmacology/Qualification-DDI-UGT/blob/master/Qualification/Input/Content/images/GFME_equation.PNG)

Or you could even use Latex 😉 
`$$ {\Huge  GMFE = 10^{\frac{\sum(|log(\frac{Pred}{Obs})|)}{n}} }  $$`

$$ {\Huge  GMFE = 10^{\frac{\sum(|log(\frac{Pred}{Obs})|)}{n}} }  $$

2023-02-16 17:42 UTC, Yuri05 commented on Input/Qualification-Ontogeny-UGT1A9.json
>                  "PKParameter": "AUC",
This is still accepted, but to make it conform with the new schema, it should be
`"PKParameters": ["AUC"],`

2023-02-17 08:26 UTC, Incei commented
@Yuri05  : Please save as UTF-8 -->so system default encoding in R-studio is ISO-88-59-1.... meaning all my other workflows are also not UTF-8....
Not sure if others adjusted that either

2023-02-17 10:18 UTC, Yuri05 commented
>Please save as UTF-8 -->so system default encoding in R-studio is ISO-88-59-1....

Please change it to UTF-8 😉 
![grafik](https://user-images.githubusercontent.com/25061876/219615334-5539af24-b5ea-4c18-8265-85403ee5c176.png)

>meaning all my other workflows are also not UTF-8.... 

As long as they don't use non-ASCII characters (like "µ" etc.) - it's not a problem.

2023-03-17 14:03 UTC, Yuri05 approved these changes

2023-03-17 14:03 UTC, merged